source "https://rubygems.org"
ruby "2.2.0"

gem "lita"

#adapter
gem "lita-slack"

#handlers
gem "lita-ascii-art"
gem "lita-baby_elephant"
gem "lita-catgif"
gem "lita-chuck_norris"
gem "lita-coin"
gem "lita-corporate-bs-generator"
gem "lita-cowsay"
gem "lita-dice"
gem "lita-dogebomb"
gem "lita-dolan"
gem "lita-down-for-everyone"
gem "lita-eightball"
gem "lita-eval"
gem "lita-flip"
gem "lita-forecast"
gem "lita-google"
gem "lita-google-images"
gem "lita-hackersays"
gem "lita-high-five"
gem "lita-howdoi"
gem "lita-karma"
gem "lita-likeaboss"
gem "lita-memegen"
gem "lita-motivate"
gem "lita-octocat"
gem "lita-pls"
gem "lita-poetry"
gem "lita-poll"
gem "lita-pugbomb"
gem "lita-responder"
gem "lita-reverse_table_flip"
gem "lita-rimshot"
gem "lita-roll"
gem "lita-shipit"
gem "lita-slack-karma-sync"
gem "lita-twss"
gem "lita-urban"
gem "lita-vader"
gem "lita-wikipedia"
gem "lita-wtf"
gem "lita-xkcd"
gem "lita-y"
